### ISSUE TITLE
DLRS (v0.4.0) has incorrect PYTHONPATH

### ISSUE THREAD

**Issue by poussa** [clearlinux/dockerfiles#235]
```bash
root@0d038e7669f4/workspace # echo $PYTHONPATH
/usr/local/lib/openvino/inference_engine/:
root@0d038e7669f4/workspace # ie_serving
Traceback (most recent call last):
  File "/usr/bin/ie_serving", line 6, in <module>
    from ie_serving.main import main
  File "/usr/lib/python3.7/site-packages/ie_serving/main.py", line 22, in <module>
    from ie_serving.models.model_builder import ModelBuilder
  File "/usr/lib/python3.7/site-packages/ie_serving/models/model_builder.py", line 18, in <module>
    from ie_serving.models.gs_model import GSModel
  File "/usr/lib/python3.7/site-packages/ie_serving/models/gs_model.py", line 18, in <module>
    from ie_serving.models.ir_engine import IrEngine
  File "/usr/lib/python3.7/site-packages/ie_serving/models/ir_engine.py", line 19, in <module>
    from openvino.inference_engine import IENetwork, IEPlugin
ModuleNotFoundError: No module named 'openvino'
root@0d038e7669f4/workspace # export PYTHONPATH=/usr/local/lib
root@0d038e7669f4/workspace # ie_serving
[finds openvino and starts]
```

https://github.com/clearlinux/dockerfiles/blob/52b2efde27e6af41fcc2e242d22141fca0f98eaf/stacks/dlrs/mkl/Dockerfile#L80

**Comment by joselamego** [comment]
@poussa: Thanks for your report.
The PYTHONPATH is fixed in image v0.4.1. Please pull that one and let me know if you encounter further errors:
```
docker pull clearlinux/stacks-dlrs-mkl:v0.4.1
```
Note that updating the Dockerfile at dockerfiles/stacks/dlrs/mkl is WIP.

**Comment by poussa** [comment]
Fixed in the 0.4.1 image. Still waiting to see the fix in the src tree.
